// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVrc9vQjwZ4xv5R-FOxeJobOgmtmpHo28',
    appId: '1:228767062357:web:ceea10e996f0db5f9b37dc',
    messagingSenderId: '228767062357',
    projectId: 'assist-56b0d',
    authDomain: 'assist-56b0d.firebaseapp.com',
    storageBucket: 'assist-56b0d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI17-LbJUTjYDJ8SHuuWaURFouYtr6nhI',
    appId: '1:228767062357:android:0b6cf4ff178285949b37dc',
    messagingSenderId: '228767062357',
    projectId: 'assist-56b0d',
    storageBucket: 'assist-56b0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_Uod8iElXdCLejvjXUBY_ucNiiY18X8',
    appId: '1:228767062357:ios:c613082430f14c279b37dc',
    messagingSenderId: '228767062357',
    projectId: 'assist-56b0d',
    storageBucket: 'assist-56b0d.firebasestorage.app',
    iosBundleId: 'com.example.provaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_Uod8iElXdCLejvjXUBY_ucNiiY18X8',
    appId: '1:228767062357:ios:c613082430f14c279b37dc',
    messagingSenderId: '228767062357',
    projectId: 'assist-56b0d',
    storageBucket: 'assist-56b0d.firebasestorage.app',
    iosBundleId: 'com.example.provaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVrc9vQjwZ4xv5R-FOxeJobOgmtmpHo28',
    appId: '1:228767062357:web:d396c07159930f9e9b37dc',
    messagingSenderId: '228767062357',
    projectId: 'assist-56b0d',
    authDomain: 'assist-56b0d.firebaseapp.com',
    storageBucket: 'assist-56b0d.firebasestorage.app',
  );

}